### ISSUE TITLE
SMTP assistant failed

### ISSUE THREAD

**Issue by Chris25-56** [prrvchr/smtpMailerOOo#2]
Hi,
I installed smtpMailer OOo on Libreoffice 7.2.7.
The installation is OK, but when I want to add an expediter, the programm freeze :
![Capture d’écran 2022-06-19 230932](https://user-images.githubusercontent.com/74775133/174876754-b9626288-4cc5-4ede-afad-70572bfe43db.jpg)
Thank you for this application which must allow a mailing from a gmail address
I use LO 7.2.7, OS : windows 10.
the extensions installed are : 
**smtpmailerOOo 0.0.2
Oauth2OOo 0.0.5**
I couldn't install **jdbcDriverOOo.oxt**
message : 
_

> (com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: io/github/prrvchr/jdbcdriver/RegistrationHandler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0\X000d\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000d\X000a\X0009at java.lang.ClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.security.SecureClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.defineClass(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader.access$100(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.net.URLClassLoader$1.run(Unknown Source)\X000d\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000d\X000a\X0009at java.net.URLClassLoader.findClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at java.lang.ClassLoader.loadClass(Unknown Source)\X000d\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000d\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000d\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

_
Could you help me ?
Thank you
Christophe

**Comment by prrvchr** [comment]
Hi Chris25-56,

Thank you for taking the time to open an issue, it helps me to improve the extension.

It seems that your version of java is 1.8, you need a **[version 11 minimum](https://adoptium.net/releases.html?variant=openjdk11)**.

I'm closing this issue, I encourage you to open another if necessary.

Edit: I advise you to install the correct version of java, to **uninstall then reinstall all the extensions**.
