### ISSUE TITLE
Having difficulty setting up

### ISSUE THREAD

**Issue by axtens** [prrvchr/smtpMailerOOo#3]
smtpMailerOOo (it says in the titlebar) is trying to find configuration for address: bruceax@gmail.com (one of my many addresses) and has got to "Mozilla IspDB search..." and has not moved from there in over an hour. It should have found [GMail](https://autoconfig.thunderbird.net/v1.1/gmail.com)'s settings quickly but hasn't. Now what?

**Comment by prrvchr** [comment]
I just updated to version 1.0.1.

This new version now displays an error message in the case where the **OAuth2OOo** and/or **jdbcDriverOOo** extensions necessary for the proper functioning of eMailerOOo **have not been installed**.

**Comment by axtens** [comment]
That hasn't made any difference to me. I have all things installed. I'm still having a lockup at the ISPDB search. I have enabled logging to file but the file is always empty.
![image](https://github.com/prrvchr/eMailerOOo/assets/209621/7c7d4473-16b4-4c57-80c7-f02a72764a3b)

**Comment by axtens** [comment]
Oddly, the OAuth2OOo.oxt keeps listing itself as 0.0.6 even though your repo says it's 1.1.1 (which I have just downloaded, updated, and restarted for.
![image](https://github.com/prrvchr/eMailerOOo/assets/209621/18b17e5e-fa3e-4f40-9161-6f7acbb07460)

**Comment by prrvchr** [comment]
**This cannot work with version 0.0.6**.

If you can't uninstall and reinstall the latest version (1.1.1), I think your LibreOffice profile is broken.
The best way to find out is to save it, delete it and create a new one.
See the information: [LibreOffice user profile](https://wiki.documentfoundation.org/UserProfile).

I think once you fix the problem, then it should work.
I would like to close this issue, you are free to open a new one if necessary.

PS: you can try to remove the extension manually by deleting the correct folder in:
**~userprofile/libreoffice/4/user/uno_packages/cache/uno_packages**
