### ISSUE TITLE
Seeking example code

### ISSUE THREAD

**Issue by axtens** [prrvchr/smtpMailerOOo#4]
I finally have managed to get everything installed properly and working ... up to a point. I was rather hoping for some demonstration code and I haven't seen much. I may not be looking in the correct location.

My client already has an application fully built and is not about to make wholesale changes to accommodate a different workflow. I have been asked simply to find an email tool that will talk to GMail via OAuth and bolt that on as simply as possible to the existing code base in place or the previous username/password email client that had been in use before.

Is it impossible simply to create a mail object, populate fields and send as one might do in C# with Microsoft's Mail libraries or via Google Apps Script and GMail? If it is impossible, please point out to me a possible solution.

**Comment by prrvchr** [comment]
Hi axtens,

> Is it impossible simply to create a mail object, populate fields and send as one might do in C# with Microsoft's Mail libraries or via Google Apps Script and GMail? If it is impossible, please point out to me a possible solution.

eMailerOOo is an extension written in Python allowing, through the use of [UNO services](https://en.wikipedia.org/wiki/Universal_Network_Objects) specific to LibreOffice, to send emails.
It is possible to write a macro (in Basic or Python), a component or an extension (in Python, Java or C) in LibreOffice which will use these UNO services in order to send emails.

eMailerOOo is not an API in the broad sense, but only an extension of LibreOffice's UNO services and will only be accessible via programs written in LibreOffice (macro, component or LibreOffice extension).

Now if this satisfies you, then I could give you some example code to send an email.

**Comment by axtens** [comment]
That would most definitely satisfy me.

**Comment by prrvchr** [comment]
The following code examples are in Python and are extracted from the code implemented in the eMailerOOo extension:

- To [send an email without attachment](https://github.com/prrvchr/eMailerOOo/blob/master/source/eMailerOOo/service/pythonpath/emailer/ispdb/ispdbmodel.py#L391) as done in the eMailerOOo ISPDB wizard with the Send email button (see screenshot)
![Test server connection](https://github.com/prrvchr/eMailerOOo/assets/7834336/b6fe8ce9-5507-4938-acff-b726719d919a)

- To [send emails optionally with attachments](https://github.com/prrvchr/eMailerOOo/blob/master/source/eMailerOOo/service/pythonpath/emailer/mailspooler.py#L192) as is done when you start the eMailerOOo spooler.

- All UNO services and the methods that these services offer are described in the idl files in the [com.sun.star.mail](https://github.com/prrvchr/eMailerOOo/tree/master/source/eMailerOOo/idl/com/sun/star/mail) folder.

**Comment by axtens** [comment]
This is harder than I thought. I can read Python a little bit. Trying to get my head into the OO environment is harder. Sadly the client's work is all in BASIC.

**Comment by prrvchr** [comment]
> Sadly the client's work is all in BASIC.

I must admit that under Basic only the methods of the [SpoolerService.idl](https://github.com/prrvchr/eMailerOOo/blob/master/source/eMailerOOo/idl/com/sun/star/mail/XSpoolerService.idl) and [MailMessage2.idl](https://github.com/prrvchr/eMailerOOo/blob/master/source/eMailerOOo/idl/com/sun/star/mail/XMailMessage2.idl) UNO services should be accessible...

Nothing exists regarding the Mozilla IspDB configuration wizard at least it is not accessible from Basic...

We should define what should be accessible from Basic, and why not integrate this into the next version?

**Comment by axtens** [comment]
Great idea. Wider audience and all that. Totally outside my skill-set however.

**Comment by prrvchr** [comment]
Well, that's it... I think it's the best Basic API that exists for sending emails.
We couldn't make it simpler...

Everything happens in the new macro that you can find in: **Tools -> Macros -> Edit Macros... -> eMailerOOo -> SendEmail**

Be careful, the macros do not work if no document is open and the version of the extension has not changed...
I'm closing, you're free to open another one if necessary...

**Comment by axtens** [comment]
Most grateful. Thank you.

**Comment by prrvchr** [comment]
Your welcome. I just updated the SendEmail macro, the example is more elaborate...
You need to re-download the extension.

**Comment by prrvchr** [comment]
I had to modify the API again so that it would be able to report us if the IspDB connection Wizard was canceled...
I think that now the API should be functional, I will let you report any malfunction...

**Comment by prrvchr** [comment]
I add another example code: [How to send an email with a Google account](https://github.com/prrvchr/OAuth2OOo/issues/19)
