### ISSUE TITLE
Issue with google workspace adresses

### ISSUE THREAD

**Issue by presb** [prrvchr/smtpMailerOOo#5]
Hello,

I tried an automatic translation with deepL. The result may not be very comprehensible, so I'm adding the original below.

I like your extension, but I can't configure it.
I followed the instructions to install it and everything seems to have worked.
When I try to configure the connection, everything stops at "Configuration found on Mozilla IspDB..."
I'm using a Google Workspace address (with a domain name other than gmail.com). Maybe that's the problem, because with a regular gmail address, I get to the end of the configuration and successfully send a test email.

Second problem (I don't know if they're related): when I click on "publish a document", I can't add a mailing list. The Add button is active, but nothing happens when I click on it. My data source is a free office workbook containing a single sheet. I've added a primary key in the form of an integer in column A. There's a header row.

I don't know what information to add, but I'll answer your questions.
Thank you for your work and your answers.

Translated with www.DeepL.com/Translator (free version)

Bonjour,

J'ai essayé une traduction automatique avec deepL. Le résultat n'est peut-être pas très compréhensible, alors je rajoute en dessous l'original.

Votre extension me plaît bien, mais je n'arrive pas à la configurer.
J'ai suivi les instructions pour l'installer et tout semble avoir réussi.
Lorsque je tente de configurer la connexion, tout s'arrête à "Configuration trouvée sur Mozilla IspDB..."
J'utilise une adresse Google Workspace (avec un nom de domaine différent de gmail.com). C'est peut-être le problème parce qu'avec une adresse gmail classique, j'arrive au bout de la configuration et j'arrive avec succès à envoyer un email de test.

Deuxième problème (je ne sais pas s'ils sont liés) : lorsque je clique "publiposter un document", je n'arrive pas à ajouter une liste de diffusion. La bouton Ajouter est actif, mais il ne se passe rien quand je clique dessus. Ma source de données est un classeur libre office contenant une seule feuille. J'ai ajouté une clef primaire sous la forme d'un entier en colonne A. Il y a une ligne d'en-tête.

Je ne sais pas quels renseignements ajouter, mais je répondrai à vos questions.
Merci pour votre travail et vos réponses.

**Comment by prrvchr** [comment]
Bonjour presb,

On va continuer en francais cela sera plus facile...

> C'est peut-être le problème parce qu'avec une adresse gmail classique, j'arrive au bout de la configuration et j'arrive avec succès à envoyer un email de test.

Il faudrait que je puisse tester sur l'adresse en question. Vous pouvez me l'envoyer par message privé à mon adresse: prrvchr@gmail.com si cela est possible évidemment.

> Ma source de données est un classeur libre office contenant une seule feuille. J'ai ajouté une clef primaire sous la forme d'un entier en colonne A. Il y a une ligne d'en-tête.

La source de donnée doit être un fichier odb de Base, puisque qu'une liste de diffusion est composé de deux requêtes SQL qui sont créés dans le fichier odb de Base. Je ne pense pas que cela soit possible avec comme source de données un fichier Calc...
Peut être essayer de convertir ce fichier Calc en fichier Base odb...

**Comment by presb** [comment]
Bonsoir et merci pour la réponse.

Pour l'adresse, je vais vous créer une adresse de test sur notre domaine si cela vous va.

En transformant le classeur en base de données, j'arrive à la sélection des destinataires. Mais je n'arrive pas à les sélectionner. Je clique sur Ajouter et il n'y a toujours rien dans l'onglet Destinataires sélectionnés.
Peut-être est-ce un problème de requête SQL ? Je ne comprends pas bien ce que vous dites : "une liste de diffusion est composé de deux requêtes SQL qui sont créés dans le fichier odb de Base". Pour l'instant, j'ai un fichier odb avec une table, qui contient mon classeur plus une clé primaire.

Edit : j'ai trouvé les deux requêtes. Et il y a une erreur : 

Code d'erreur: -70

Cannot be in ORDER BY clause in statement [SELECT "parents 2".* FROM ( SELECT "Liste".* FROM "Liste" WHERE ( "mail" IS NOT NULL ) ORDER BY "ID" ) AS "parents 2" WHERE ( "ID" IS NULL ) OR ( "ID" = 1 )]

Bonne soirée et merci.

**Comment by presb** [comment]
Suite de mes recherches.

La configuration du protocole OAuth2 ajoutée par l'extension OAuth2OOo fonctionne avec un compte Google Workspace.
La fenêtre de connexion de google s'ouvre et le processus semble arriver au bout sans encombre.
Avec l'extension eMailerOOo, en utilisant la même adresse, je reste bloqué au même endroit.

**Comment by prrvchr** [comment]
> En transformant le classeur en base de données, j'arrive à la sélection des destinataires. 

J'ai bien peur que ce fichier odb soit géré par la base de données HsqlDB 1.8 qui est fourni par LibreOffice (**HSQLDB intégré**).
Il faut s'assurer que cette base de données est créer par l'extension jdbcDriverOOo, soit en suivant les menus:
**Fichier -> Nouveau -> Base de données -> Connecter une base de données existante -> Pilote HsqlDB**

![Nouvelle base de données](https://github.com/prrvchr/eMailerOOo/assets/7834336/b621c7f8-041a-4dbd-a7bc-2ccb7ee73982)

> Avec l'extension eMailerOOo, en utilisant la même adresse, je reste bloqué au même endroit.

Il doit y avoir un problème dans l'extension eMailerOOo, quelle est le nom de domaine utilisé?

**Comment by prrvchr** [comment]
Je viens de publier [eMailerOOo version 1.0.2](https://prrvchr.github.io/eMailerOOo/#what-has-been-done-for-version-102) qui résout le problème d'utilisation d'une adresse Google workspace.
Ce domaine n'existant pas dans la base de données Mozilla IspDB, vous devrez configurer les serveurs (SMTP et IMAP) manuellement.

**Comment by prrvchr** [comment]
Je viens de corriger la nouvelle version 1.0.2, celle-ci désormais sauvegarde correctement tout domaine n'existant pas dans la base de données Mozilla IspDB.

**Comment by presb** [comment]
Bonjour,

la nouvelle version marche à merveille. J'ai réussi à configurer et à envoyer le message de test. Mille mercis !

Du côté du pilote de base de données, j'ai installé un JRE (adoptium 11) et l'extension jdbcDriverOOo 1.0.5 et suivi les consignes trouvées sur github en mettant file:///c:/tmp/testdb;shutdown=true;hsqldb.default_table_type=cached;get_column_name=false dans la case prévue. La base de données est créée sans problème.
En revanche, quand j'essaie de coller le contenu de mon tableur, LibreOffice plante à chaque fois. Ça marchait pourtant avec le pilote natif de LibreOffice.

**Comment by prrvchr** [comment]
> la nouvelle version marche à merveille. J'ai réussi à configurer et à envoyer le message de test. Mille mercis !

Tant mieux. Des améliorations restent à apporter dans ce mode de configuration manuelle de l'assistant de configuration des connexions. Je les implémenterai dans une prochaine version.

 > En revanche, quand j'essaie de coller le contenu de mon tableur, LibreOffice plante à chaque fois. Ça marchait pourtant avec le pilote natif de LibreOffice.

Je n'ai jamais essayé cette fonctionnalité et je suis prêt à examiner le problème.
Par contre, je préfère clôturer ce dysfonctionnement et vous demande d'en ouvrir [un nouveau pour ce problème précis](https://github.com/prrvchr/jdbcDriverOOo/issues/new/choose). Merci de me preciser comment reproduire ce dysfonctionnement.
