### ISSUE TITLE
Support personalized subject line in mail merge dialog

### ISSUE THREAD

**Issue by davido** [prrvchr/smtpMailerOOo#6]
I am looking for the possibility to have personalized subject line in mail merge function.

Suppose the data source have a column called `subject` and I would like to be able to reference this field in the send mail merge dialog, e.g. `<subject>`. Or generally speaking reference combined fields, e.g.: `foo <field1> bar <field2>`. 

It seems that there is  another extension available to provide this feature, but not for LibreOffice: [1].

Another option would be to support this feature in core mail merge feature of LibreOffice.

[1] https://www.mapilab.com/blog/how-to-customize-subject-line-in-mail-merge-toolkit-for-outlook/

**Comment by prrvchr** [comment]
Hi davido,

It's a good idea, I'm preparing version 1.1.0 which meets the needs of issue #4. I will try to integrate such functionality.

**Comment by davido** [comment]
@prrvchr 

> I will try to integrate such functionality.

:+1:

**Comment by prrvchr** [comment]
Ok, done...

see [What has been done for version 1.1.0](https://prrvchr.github.io/eMailerOOo/#what-has-been-done-for-version-110)

I close the issue but do not hesitate to open a new one if necessary.
