### ISSUE TITLE
Comment utiliser un fichier Calc comme source de données

### ISSUE THREAD

**Issue by presb** [prrvchr/smtpMailerOOo#9]
Bonjour,
Je n'arrive pas à envoyer des mails avec l'extension. Je ne suis malheureusement pas capable de dire si c'est un bug ou si je l'ai mal configurée. Désolé.

Mon document Writer est prêt. Les champs font référence à une base odb. Mais la base n'apparaît pas bien dans Outils > Sources du carnet d'adresses.
![image](https://github.com/user-attachments/assets/2056bda5-c746-4a99-8b02-5ed3ceec315c)

Tel quel, je peux quand même essayer et ça a l'air de marcher.
![image](https://github.com/user-attachments/assets/9171c8f5-d5df-4603-992b-e9c8b72e70d4)

L'envoi est un échec. Néanmoins, il a bien essayé d'utiliser l'adresse dans ma base de données, qui semble donc être correctement liée, quoi qu'il en semble dans les sources du carnet d'adresses. Voici le message d'erreur :

<class 'AttributeError'>: hasCcRecipients, traceback follows
  File "C:\Users\sjbde\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu13761hzyxo.tmp_\eMailerOOo(1).oxt\service\pythonpath\emailer\mailservice\smtpservice.py", line 144, in sendMailMessage
    self._sendSmtpMailMessage(message)
  File "C:\Users\sjbde\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu13761hzyxo.tmp_\eMailerOOo(1).oxt\service\pythonpath\emailer\mailservice\smtpservice.py", line 328, in _sendSmtpMailMessage
    recipients = self._getRecipients(message)
  File "C:\Users\sjbde\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu13761hzyxo.tmp_\eMailerOOo(1).oxt\service\pythonpath\emailer\mailservice\smtpservice.py", line 365, in _getRecipients
    if message.hasCcRecipients():

 at C:/cygwin64/home/buildslave/source/libo-core/pyuno/source/module/pyuno_runtime.cxx:950

Merci d'avance pour votre aide.

**Comment by prrvchr** [comment]
Bonjour presb,

> Mon document Writer est prêt. Les champs font référence à une base odb. Mais la base n'apparaît pas bien dans Outils > Sources du carnet d'adresses.

Il est impératif que la source de données soit enregistrée dans la liste des sources de données accessibles dans: **Outils -> Options... -> LibreOffice Base -> Base de données**. C'est la colonne `Nom enregistré` qui doit être utilisé dans: **Outils -> Sources du carnet d'adresses** du document de fusion Writer et dans l'assistant de publipostage de eMailerOOo.

> Tel quel, je peux quand même essayer et ça a l'air de marcher.

Cette boîte de dialogue ne provient pas de eMailerOOo. Pour publiposter un document Writer, il faut:
- un document Writer ouvert avec les champs de fusion correctement insérés.
- Lancer le publipostage par le menu: **Outils -> Add-ons -> Envoi de courriels -> Publiposter un document**
- Puis suivre les étapes de l'assistant de publipostage (voir la documentation)

Par contre, eMailerOOo n'a pas encore été mis à jour pour prendre en charge la version 24.8.x de LibreOffice.
Mais cela va être bientôt fait...

**Comment by presb** [comment]
Merci de votre réponse.
J'ai rectifié la configuration pour la source de données.
J'attends la mise à jour de l'extension pour refaire un essai.
Bonne journée.

**Comment by prrvchr** [comment]
Voila, pour fonctionner avec LibreOffice 24.8.x sous Windows 10 (32 ou 64 bits) il faut au minimum:

- OAuth2OOo version 1.3.7
- jdbcDriverOOo version 1.4.5
- eMailerOOo 1.2.5

Pour essai j'ai réussi à envoyer un mailing avec LibreOffice 24.8.0.3 / Windows 10 (64bits) sous Lubuntu / VirtualBox.
Merci de me confirmer que cela fonctionne pour vous.

**Comment by presb** [comment]
Mises à jour de eMailerOOo et jdbcDriverOOo faites. Je n'arrive toujours pas à envoyer de mail.
La source de données a l'air bien enregistrée.
Quand je lance le publipostage, tout semble bien se passer : 
![image](https://github.com/user-attachments/assets/eb20cc7d-3179-4d54-bd70-2ecaf08edf9c)

A l'étape d'après, le contenu de ma base apparait dans l'onglet Destinataires disponibles, mais je n'arrive pas à les faire passer dans Destinataires sélectionnés qui reste vide. Quand je sélectionne un contact et que je clique sur ajouter, il change de couleur, mais rien ne se passe.

Pour la mise à jour de jdbcDriverOOo, suffit-il d'installer la nouvelle version après avoir désinstallé l'ancienne, ou faut-il faire quelque chose de plus ?

Cordialement

**Comment by prrvchr** [comment]
> Quand je sélectionne un contact et que je clique sur ajouter, il change de couleur, mais rien ne se passe.

Normalement ce contact devrait se retrouver dans l'onglet **Destinataire sélectionné** et le bouton **Suivant** devrait devenir activé (non grisé)

J'ai peur que le probleme provienne de la source de données, pourriez-vous, à votre convenance :
- Faire un test avec l'extension gContactOOo comme source de données (il est nécessaire d'avoir un compte Google).
- Ou m'envoyer une copie de votre source de données avec un contenu anonymisé de 3 enregistrements.

**Comment by presb** [comment]
Bonsoir,
J'ai essayé d'utiliser gContactOOo, mais j'ai du mal...
Le problème doit probablement venir de la source de données.
Je me propose de la recréer à partir de zéro. J'ai tout supprimé (le fichier de base de donnée et la base dans la liste des bases de données connues par libreoffice). J'ai un fichier LibreOffice calc avec mon tableau, et je le transforme en base de données, en créant une nouvelle base vide, puis en collant ma feuille de données dans la zone tables. Cela me propose de créer une nouvelle table, ce que je fais. Je sauvegarde.
![image](https://github.com/user-attachments/assets/2edc8ba0-83c5-4b1a-bac1-c99465a36f01)

![image](https://github.com/user-attachments/assets/7ea44896-7585-49e3-9729-e883722b9273)

![image](https://github.com/user-attachments/assets/9695c4c4-f682-47f1-97a0-feeb0f1da66f)

A ce moment, ma base est référencée, et je peux la sélectionner dans outils > sources du carnet d'adresses
![image](https://github.com/user-attachments/assets/2a22d5db-6483-4e5b-9a70-5a32e06c0800)

Ensuite je lance eMailerOOo
![image](https://github.com/user-attachments/assets/186bd950-8431-47bf-80c6-7e5360cca510)

![image](https://github.com/user-attachments/assets/54c00a39-e7dc-46ba-87dc-0209bbfb1f16)

Et je retrouve le même problème.
Je vous joindrais bien un fichier de base de données mais je n'y arrive pas : type de fichier non supporté...

Merci pour votre aide.

**Comment by prrvchr** [comment]
En regardant de plus prés votre première capture d'écran, vous semblez vouloir utiliser **HSQLDB intégré**.
Ceci n'est pas possible: cette base de données est complètement obsolète (ie: HsqlDB version 1.8.1).

Si vous souhaitez utiliser une base de données HsqlDB intégré, vous devez installer l'extension [HyperSQLOOo](https://prrvchr.github.io/HyperSQLOOo/README_fr) (ie: HsqlDB version 2.7.3).

Par contre dans votre troisième capture d'écran, dans **Nom de la table:**, vous devrez mettre: **PUBLIC.PUBLIC.Liste** à la place de: **Liste**.
De la même façon, dans votre quatrième capture d'écran, dans **Table:**, vous devrez mettre: **PUBLIC.PUBLIC.Liste** à la place de: **Liste**.

Et enfin, tous les documents Writer (ie: le contenu du courriel et les fichiers attachés) ne doivent contenir que des champs de fusion (ie: colonnes) relatifs à la table: **PUBLIC.PUBLIC.List**.

Si votre document Writer a été configuré correctement (ie: **Outils -> Sources du carnet d'adresses**), dans votre cinquième capture d'écran, la **Source de données :** `C2S` doit être **automatiquement** sélectionnée.

**Comment by presb** [comment]
> Si vous souhaitez utiliser une base de données HsqlDB intégré, vous devez installer l'extension [HyperSQLOOo](https://prrvchr.github.io/HyperSQLOOo/README_fr) (ie: HsqlDB version 2.7.3).

Je ne souhaite pas particulièrement utiliser HsqlDB intégré. Que me conseillez-vous d'utiliser ? Est-il indispensable d'utiliser une extension de plus ?

> Par contre dans votre troisième capture d'écran, dans **Nom de la table:**, vous devrez mettre: `PUBLIC.PUBLIC.Liste` à la place de: `Liste`

Je vais tester. Mais par curiosité, qu'est-ce que l'ajout du préfixe PUBLIC.PUBLIC change ?

> Si votre document Writer a été configuré correctement (ie: **Outils -> Sources du carnet d'adresses**), dans votre cinquième capture d'écran, la **Source de données :** `C2S` doit être **automatiquement** sélectionnée.

C'est le cas il me semble.

**Comment by prrvchr** [comment]
> Je ne souhaite pas particulièrement utiliser HsqlDB intégré. Que me conseillez-vous d'utiliser ? Est-il indispensable d'utiliser une extension de plus ?

En fait vous n'avez pas vraiment le choix, il faut un fichier odb pour faire fonctionner eMailerOOo et cela ne peut pas fonctionner avec HsqlDB 1.8.x...
Plus précisément, la fonction principale de l'extension [HyperSQLOOo](https://prrvchr.github.io/HyperSQLOOo/README_fr) est de pouvoir utiliser HsqlDB 2.7.3 dans un fichier odb. Elle vous permettra d'utiliser votre fichier Calc comme source de données au lieu de l'extension gContactOOo par exemple (ie: une source de données HsqlDB 2.7.3 synchronisée avec vos contacts Google).

> Je vais tester. Mais par curiosité, qu'est-ce que l'ajout du préfixe PUBLIC.PUBLIC change ?

Si vous utiliser HyperSQLOOo alors il est indispensable de nommer la table de son nom complet: **NomCatalogue.NomSchema.NomTable**. Voir les prérequis de mon message précédent.

**Comment by prrvchr** [comment]
Bon en l'absence de réponse je vais considérer comme résolu.

En tout cas j'ai vérifié: **il est possible de créer une nouvelle source de données avec HyperSQLOOo et de copier le contenu d'un fichier Calc via l'assistant que propose LibreOffice**. Pour le faire vous devez:
- Installer HyperSQLOOo et [créer une nouvelle base de données](https://prrvchr.github.io/HyperSQLOOo/README_fr#comment-cr%C3%A9er-une-nouvelle-base-de-donn%C3%A9es) HsqlDB.
- Dans Calc selectionner une plage de cellules puis: **Edition -> Copier**.
- Dans Base (ie: la nouvelle base de données HsqlDB), aprés avoir selectioné `Tables` dans le volet `Database`, clic droit dans le volet `Tables` puis: **Coller** et suivre l'assistant que propose LibreOffice. **Il est important de nommer la table avec un nom complet** (ie: **PUBLIC.PUBLIC.Table1**). Voir la [documentation](https://hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_schemas_schema_objects) HsqlDB à propos du **catalogue et schéma par défaut**.

**Comment by presb** [comment]
Bonsoir,
J'ai décroché quelques jours. Débordé en début d'année...
Quand j'essaye de suivre votre dernier message, j'ai une erreur :
![image](https://github.com/user-attachments/assets/e7cb72c5-de06-49db-9876-d205668d698f)

Je crois avoir suivi à la lettre les instructions. Au début, je ne pouvais pas coller dans base. Après avoir supprimé les anciennes bases de données référencées, ça remarche, mais j'obtiens toujours l'erreur.
J'ai essayé de réinstaller les extensions. J'ai mis à jour LibreOffice vers la dernière version (24.8.1.2), ça ne change rien.
Voici l'état de mon installation actuelle : 
![image](https://github.com/user-attachments/assets/3bf55765-76b1-4034-b670-896f27b216bd)
J'ai activé les journaux des extensions HyperSQLOOo et jdbcDriverOOo. Après redémarrage, j'obtiens ces journaux quand je reproduis l'erreur :
Celui de HyperSQL OOo
![image](https://github.com/user-attachments/assets/06bd2d26-e9ca-42a8-b216-1584b679c577)
Pour jdbcDriverOOo, la fenêtre défile tant que je n'ai pas quitté la page d'erreur. Ensuite, j'obtiens ça (trop long donc je vous mets le fichier) :
[io.github.prrvchr.jdbcDriverOOo.Driver.log](https://github.com/user-attachments/files/17102796/io.github.prrvchr.jdbcDriverOOo.Driver.log)

Merci de votre aide.

**Comment by prrvchr** [comment]
> ERREUR lors de création de la table <TableContainer #0> avec la requête PUBLIC.SA.Table1

Étant donné le message d'erreur, êtes-vous sûr d'avoir mis **PUBLIC.PUBLIC.Table1** comme nom de table et pas seulement **Table1**?
Avec HsqlDB, l'unique catalogue s'appelle par défaut **PUBLIC** et le seul schéma existant par défaut s'appelle **PUBLIC**. J'ai ajouté des explications supplémentaires dans mon message précédent.

Sinon, envoyez-moi une copie des écrans de l'assistant que LibreOffice ouvre lorsque vous collez le contenu de Calc dans Base.

**Comment by presb** [comment]
Voilà :
![image](https://github.com/user-attachments/assets/f90d7f7a-e0a3-4cf2-8ab3-c0bfd70ad4ef)

![image](https://github.com/user-attachments/assets/2b34aacb-d7ae-49ff-8f21-aa3293f3b3df)

![image](https://github.com/user-attachments/assets/2f76c1d1-8a75-4226-af8a-37a30a1da6f2)

Maintenant je n'ai plus d'erreur. Mais j'obtiens une table vide.
![image](https://github.com/user-attachments/assets/e441ee9e-ae02-4dfe-bbb7-a0d9c7f0adfe)

**Comment by prrvchr** [comment]
Je n'arrive pas à reproduire votre problème. Si je nomme correctement la table alors l'import se passe bien et la table est remplie.

Peut-être que le problème vient du contenu de votre fichier Calc. Essayez avec un jeu réduit à un minimum de trois colonnes (ie: nom, prénom et mail) et de seulement deux enregistrements...

Je vous joins le fichier Calc avec lequel ma tentative d'importation se déroule bien, et dites moi si vous arrivez à l'importer?
[Mes Contacts.ods](https://github.com/user-attachments/files/17139119/Mes.Contacts.ods)

Et enfin, je vous conseille de laisser le type par défaut (ie: INTEGER) pour la colonne ID que l'assistant crée, ou si le nombre d'enregistrements le nécessite le type BIGINT.

**Comment by presb** [comment]
Effectivement, j'ai essayé sur un autre poste, sous Linux, et le contenu s'est collé. Mais ça ne marche pas pour autant, car j'ai des problèmes au niveau du python. Mais je n'ai pas le même problème que sur ce PC.
Votre fichier donne le même résultat que l'autre. Tout se passe bien, et rien dans la base de données. Malheureusement, cela veut dire que mon problème risque de ne pas être simple à résoudre...

Demain j'essayerai de réinstaller (LibreOffice et toutes les extensions). Et supprimer le profile. Avez-vous d'autres idées ?

En tout cas, ce n'est pas votre extension qui est fautive et je vous remercie de votre patience et du temps pris pour résoudre mes problèmes.
Bonne soirée.

**Comment by prrvchr** [comment]
Bon je viens de faire quelques tests supplémentaires mais cette fois sous **LibreOffice 24.8.x / Windows 10** avec VirualBox sous Lubuntu et effectivement **les imports ne fonctionnent pas** (ie: ils sont vides). Cela semble lié à LibreOffice sous Windows.

Je dois faire plus d'investigations pour savoir d'ou cela vient.

**Comment by presb** [comment]
La réinstallation ne change rien.
En attendant je vais me tourner vers Linux. J'ai une autre machine sous debian stable. En revanche, je n'ai pas les dépendances Python. Quand j'essaye de les installer avec pip, j'ai un message d'avertissement me disant que je risque de casser mon système. A ce que j'ai vu, debian utilise python pour un certain nombre de choses, et donc python fait partie du système. Avant de faire des bêtises, je pose la question (puisqu'il semble que vous soyez sur ubuntu) : comment faites-vous pour avoir un environement python convenable ?

**Comment by prrvchr** [comment]
> La réinstallation ne change rien.

Non, pour l'instant **seul LibreOffice sous Linux** (et peut être Mac) **peut importer un fichier Calc**.

>  En revanche, je n'ai pas les dépendances Python...

Version courte: Sous Debian concernant les dépendances Python tout devrait fonctionner tel quel.

Version longue:

**Toutes les dépendances Python sont déja livrées avec les extensions** (OAuth2OOo, jdbcDriverOOo...).

Concernant l'utilisation de Python par LibreOffice, on a deux possiblilités:
-  Sous Windows LibreOffice fourni une version de Python (ie: Python 3.8.x pour LibreOffice 7.x et 24.2.x, Python  3.9.x pour LibreOffice 24.8.x...)
- Sous Linux, LibreOffice ne fournit pas Python et recherche celui disponible sur le système qui, pour satisfaire les extensions, doit être de version comprise entre 3.8.x et 3.12.x.

Donc le seul problème que vous pouvez rencontrer sous Linux est :
- Que la version Python du système ne soit pas une version 3.8.x ou supérieure.
- Que vous ayez déjà installé sous Linux (généralement avec l'aide de pip) une dépendance fournie par une des extensions dans une version inférieure à celle de l'extension. D'ailleurs cela est vérifiable dans la journalisation accessible dans les options de l'extension. En fait, **les dépendances système ont précédence sur les dépendances fournies par les extensions**.

Sur Debian je pense que vous n'avez rien à faire (à moins que vous n'ayez déjà installé sur le système une des dépendances utilisées par une des extensions dans une version inférieure ce qui à mon avis est peu probable).

**Comment by presb** [comment]
Bonjour,
Je reprends le dossier...
Sous Debian, ça marche mieux, mais pas encore complètement.
Je suis arrivé à importer ma base de données depuis calc dans base. Ensuite, les premières étapes de l'utilisation de eMailerOOo se passent bien. Arrivé à la sélection des destinataires, la fenêtre où la base de données s'affiche est incomplète : le champ ID est vide. Pourtant il est bien rempli dans la base. Je ne peux pas sélectionner certains contacts (est-ce à cause de ce champ manquant ?) mais je peux les sélectionner tous. En revanche, aucun message ne part à la fin. En regardant le journal, il y a un problème avec l'ID manquant.

Des idées ?
Je crois avoir suivi les étapes comme il faut, en même temps, en voyant le nombre d'erreurs que j'ai déjà faites...

Merci pour votre aide.

**Comment by prrvchr** [comment]
> le champ ID est vide. Pourtant il est bien rempli dans la base

Quel est le type de la colonne ID dans la base de données ? La documentation eMailerOOo spécifie une colonne de type INT ou VARCHAR (ou dérivé). Elle doit également avoir la contrainte non nulle. Est ce que vous arrivez à affecter cette colonne ID comme colonne de clef primaire dans la première étape de l’assistant Publipostage de courriels?

Aprés plusieurs essais je me suis appercu qu'il est possible d'importer un fichier Calc sous Windows. Comme contournement il suffit avant l'importation de basculer le pilote jdbcDriverOOo en mode sdbcx (ie: **Outils - > Options... -> LibreOffice Base -> Pilote JDBC pur Java -> Services UNO -> Niveau connection -> com.sun.star.sdbcx.Connection**).
Il est nécessaire de fermer tous les documents ODB de Base pour que cette modification prenne effet.

**Comment by presb** [comment]
Le champ est de type NUMERIC. Et il est bien clef primaire, dans la base de données, et lors de la première phase du publipostage.
Si je me souviens bien, il a été créé lors de l'import du fichier calc. Dans l'assistant de LibreOffice, il y a la possibilité de rajouter une clef primaire.

Demain, j'essayerai de refaire ma base avec une clef primaire de type INT et non nulle. Et je referai un essai sous windows.

Merci et bonne nuit.

**Comment by presb** [comment]
Ca y est ! J'ai réussi à envoyer un mail. Il me reste à savoir en obtenir le résultat recherché (pièce jointe en pdf, et tout ça...)

Compte-rendu : j'ai recréé la table dans la base de données en spécifiant mieux le champ ID pour la clef primaire (INTEGER). J'ai aussi nettoyé les requêtes qui s'étaient accumulées au fur et à mesure des essais sans que je m'en rende compte. Qu'est-ce qui a été déterminant, je ne sais pas.

Merci infiniment pour votre aide. Je reviendrai vous donner les dernières nouvelles de mes essais sous windows.

**Comment by prrvchr** [comment]
> J'ai aussi nettoyé les requêtes qui s'étaient accumulées au fur et à mesure des essais sans que je m'en rende compte.

Je pense que cela pourrait être aussi la source de votre problème.
Après des tests, il peut également être important de nettoyer les sources de données susceptibles de s'accumuler.  (ie: **Outils -> Options... -> LibreOffice Base -> Base de données**)

Je ne sais pas combien d'enregistrements vous espérez avoir dans votre source de données, mais une clé primaire de type BIGINT pourrait être quelque chose à considérer.

Merci de me confirmer le bon fonctionnement pour que je puisse fermer.

**Comment by prrvchr** [comment]
Bon, sans aucune nouvelle, je ferme.
